server:
  port: 8888

eureka:
  client:
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

spring:
  profiles:
    active: native

#  cloud:
#    config:
#      server:
#        git:
#          uri: https://github.com/xuminwlt/config-repo